### ISSUE TITLE
Will the scripts for fine tuning on Tabfact be released recently?

### ISSUE THREAD

**Issue by leezythu** [microsoft/Table-Pretraining#1]
I saw that the script of table fact verification would be released by Sep. 5, but it is not ready for now. When are you going to present it? Thanks a lot.

**Comment by SivilTaram** [comment]
@leezythu Hi, thanks for your interest on our work! We will release it ideally by Sep. 30, since I'm recently busy with looking for job. I will get back here if it is completely ready. Thanks for your patience in advance.

**Comment by SivilTaram** [comment]
@leezythu Hi, we have released the model and script on table-based fact verification. Hope you enjoy it ☕
