### ISSUE TITLE
aggregate operator in model_interface.py

### ISSUE THREAD

**Issue by apurvak** [microsoft/Table-Pretraining#11]
Hi,
Thank you for providing the code. I have tried the sample interface provided for online prediction and it worked.
Question: currently, I don't know how the model will return the aggregate operator. For example:

For following example, the wikisql data has aggregator function like AVG. How is this returned by model? 
```
 question = "What is the average Nations? " <-- The model should return AVG(14,24,12,201,204,204) 
    table_context = {
        "header": ["Year", "City", "Country", "Nations"],
        "rows": [
            [1896, "Athens", "Greece", 14],
            [1900, "Paris", "France", 24],
            [1904, "St. Louis", "USA", 12],
            [2004, "Athens", "Greece", 201],
            [2008, "Beijing", "China", 204],
            [2012, "London", "UK", 204]
        ]
    }
```

**Comment by SivilTaram** [comment]
@apurvak Thanks for your interest on our work! TAPEX currently predicts the answer in an end-to-end manner, which does not consider if the answer is a cell in a table or an aggregated value. In other words, in the case of the provided example, the model will directly return the number of the averaged nations (but we cannot know it is computed by "average"). And thus our model is evaluated on the WikiSQL-Weak (which only provides the final answer, without any logic form). Follow-up questions are warmly welcome!
