### ISSUE TITLE
fairseq version does not exist

### ISSUE THREAD

**Issue by Harry-hash** [microsoft/Table-Pretraining#13]
fairseq@git+git://github.com/pytorch/fairseq@801a64683164680562c77b688d9ca77fc3e0cea7 seems to be not existing, could you update another version that is compatible to the code? Thanks a lot!

**Comment by SivilTaram** [comment]
@Harry-hash Thanks for your interest on our work! Since fairseq has not released their `v1.0.0` until now and I cannot guarantee the stableness of the master branch, I still recommend you to install the `801a64` version. To install it, you should first install `Git`.

**Comment by SivilTaram** [comment]
@Harry-hash Hello, anything esle I can help?

**Comment by Harry-hash** [comment]
Sorry for the late reply! Thanks a lot for generous help!
