### ISSUE TITLE
fairseq的代码clone不了，faireseq的那个连接访问不了

### ISSUE THREAD

**Issue by CharlesLao** [microsoft/Table-Pretraining#22]
你好，我在安装你公开的那个版本的fairseq时候，总是访问不了那个连接，fairseq好像也没有1.0的版本，请问可以公开一下你们的fairseq的版本吗？

**Comment by SivilTaram** [comment]
@CharlesLao Hello，我更新了fairseq的安装方法，可以再检查下。
