### ISSUE TITLE
get "samples have invalid sizes and will be skipped, max_positions=(512, 512)" when training

### ISSUE THREAD

**Issue by liushz** [microsoft/Table-Pretraining#25]
First, thanks for your great job.
I get 
`WARNING | fairseq.tasks.fairseq_task | 6,694 samples have invalid sizes and will be skipped, max_positions=(512, 512), first few sample ids=[11595, 7191, 8792, 9399, 5120, 1831, 8568, 3430, 597, 11937]`
and the same WARNING for the train set when I train a **bart-large model** with the default parameters, it looks like the model skip many examples because the **max_positions=(512, 512),** 
How can I solve this warning?  Thanks.

**Comment by SivilTaram** [comment]
@liushz Thanks for the interest on our work! I'm a little confused since the maximum source position should be set as `1024` as below:

https://github.com/microsoft/Table-Pretraining/blob/main/examples/tableqa/run_model.py#L77

Can you explain more on the message? Which script are you using? Thanks!

**Comment by liushz** [comment]
> 

Thanks for your quick reply, I use this script:
microsoft/Table-Pretraining/blob/main/examples/tableft/run_model.py
It looks like there is no "max-source-positions" in the script
Is there supposed to be no such parameter here？

**Comment by liushz** [comment]
@SivilTaram

**Comment by liushz** [comment]
I add **"--max-positions 1024"** to the args of tableft run_model.py, it seems like the problem fixed

**Comment by SivilTaram** [comment]
@liushz Glad to hear that! I will set it in the running script - maybe the default max positions has been changed in fairseq.
