### ISSUE TITLE
Question about cell truncation and answer truncation

### ISSUE THREAD

**Issue by yuhaozhang** [microsoft/Table-Pretraining#26]
Hi, thank you for the nicely written repo and the nice work!

I am reading through the part on table truncation and have a question about how cell and answer truncations are performed for long cells. Specifically, you have:
- https://github.com/microsoft/Table-Pretraining/blob/da8bbdf98857a21335379eedc74836809c22c9b9/tapex/processor/table_processor.py#L18 which truncates cells up to a certain number of tokens, and
- https://github.com/microsoft/Table-Pretraining/blob/da8bbdf98857a21335379eedc74836809c22c9b9/tapex/processor/table_processor.py#L31 which processes the answers without any explicit truncation.

My question is that for an answer that may come from a very long cell, if I understand correctly, the cell might already be truncated, yet the answer still remains the original length, right? This may not be an issue for testing/inference, but may be an issue during training, because in this case we are asking the model to generate things that do not exist in the input (because some tokens were truncated).

Is this a known limitation, or am I missing something? If it is a known limitation, is there an easy way I can remedy this using this codebase? Thanks for your time.

**Comment by SivilTaram** [comment]
Hi @yuhaozhang , thanks for your interest on our work! The intention of cell-level truncation is to truncate some too long cell values to avoid it occupying too many tokens in the input sequence (e.g., a description about a book). And for the output side, I think the following code has applied the same truncation on answers:
https://github.com/microsoft/Table-Pretraining/blob/da8bbdf98857a21335379eedc74836809c22c9b9/tapex/processor/table_truncate.py#L62

The only problem may be recovery. If you’d like to recover the original cell with post-processing, I would recommend to maintain a cell mapping dictionary by yourself.

Best,
Qian

**Comment by yuhaozhang** [comment]
Thanks for the clear response! @SivilTaram

Indeed that I overlooked this part. So the answers list will be modified in-place with the same truncation applied to the table cells. Nice work!
