### ISSUE TITLE
How to prepare our own custom data? 

### ISSUE THREAD

**Issue by tushark01** [microsoft/Table-Pretraining#27]

**Comment by SivilTaram** [comment]
@tushark01 Hello, thanks for your interest in our work! Sorry for that I am not quite sure about the question. Do you mean how to prepare your own custom pre-training data, or the fine-tuning data?

**Comment by SivilTaram** [comment]
If you would like to reproduce the data generation procedure in our paper, you may be interested in [this script](https://github.com/microsoft/Table-Pretraining/tree/main/data_generator)

**Comment by tushark01** [comment]
> @tushark01 Hello, thanks for your interest in our work! Sorry for that I am not quite sure about the question. Do you mean how to prepare your own custom pre-training data, or the fine-tuning data?

Yes, i mean how to prepare our own custome pre-training data, can we use json instead of .db files ?

**Comment by SivilTaram** [comment]
@tushark01 Thanks for your great question! For the current codebase, it cannot. But I am developing a synthesis script to support flexible pre-training corpus generation. I will ping you once it is done (the ETA is in two weeks).

**Comment by KartikSharma907** [comment]
@SivilTaram Can we prepare a custom dataset using CSV files or Pandas Dataframe? And is there a way we can return "Answer Not found in the data" when there is no answer for that particular query? Maybe we can set a threshold of predicted probabilities below which it will return Not found as the answer?

**Comment by SivilTaram** [comment]
@KartikSharma907 Thanks for the insightful question! I'm still working on the standard pre-training corpus based on pandas dataframe and it should be ready soon! Will ping you if it is ready. As for the "Answer not found in the data", would you mind sharing some use cases which should require such kind of capabilities? Maybe I can try to synthesize some data which cannot be executed in the table but not sure!

**Comment by KartikSharma907** [comment]
@SivilTaram Thanks for your quick reply! For example, I have a corpus of tabular data on which I have built my Question Answering System, and I have a query for which no answer is present. Fine-tuned Tapex model returns some arbitrary answer from the table that is wrong instead of simply returning "Not Found." This won't be possible if the model returns a wrong answer with a very high probability, as the Tapas model does. 
Also, I have some tabular data on which I want to finetune Tapex-finetuned-wtq; how to prepare this dataset into a compatible format for fairseq?

**Comment by SivilTaram** [comment]
@KartikSharma907 If you want to continually fine-tune the model, I would recommend you to use the fine-tuning script of tapex on Huggingface to achieve the goal. It contains the whole pipeline of fine-tuning, including the dataset processing (it is easy to do so in your dataset), model fine-tuning and model evaluation. More details can be found in https://github.com/huggingface/transformers/tree/main/examples/research_projects/tapex
