### ISSUE TITLE
How large the table can be handled by this model?请问该模型可以处理多大规模的表格？

### ISSUE THREAD

**Issue by twzhyyxwhez31057** [microsoft/Table-Pretraining#28]

**Comment by SivilTaram** [comment]
@twzhyyxwhez31057 Hi, thanks for your question. Usually the model can proceed tables with less than 100 rows. More rows will be truncated for memory requirement. If you are looking for a model to handle large database, you may try to use [UniSAR](https://github.com/microsoft/ContextualSP/tree/master/unified_parser_text_to_sql)
