### ISSUE TITLE
It takes a very long time to execute

### ISSUE THREAD

**Issue by HiJason** [microsoft/Table-Pretraining#29]
![image](https://github.com/microsoft/Table-Pretraining/assets/48542777/721f2c75-17b4-43f2-a83e-c7a7a5bcd5bb)
It takes a very long time to execute, I would like to know why.

**Comment by SivilTaram** [comment]
@HiJason Thanks for your interest on our work! Since you may use the default script to generate dataset, it may synthesize 5 million examples. Since many SQL queries return empty results, so it takes a long time to execute. You may try to synthesize a mucher smaller corpus if you want to accelerate it.

**Comment by HiJason** [comment]
> @HiJason Thanks for your interest on our work! Since you may use the default script to generate dataset, it may synthesize 5 million examples. Since many SQL queries return empty results, so it takes a long time to execute. You may try to synthesize a mucher smaller corpus if you want to accelerate it.

Thanks for your reply. I have tried to reduce the file in the path "data_generator/squall/tables/db" and file in the path "data_generator/squall/tables/json", only 1 file left in each path, and then run the script main.py by default, but it still takes very long time to wait.

**Comment by SivilTaram** [comment]
@HiJason yes that's true since the numbers depend on the number of template SQLs (defined in squall dataset) and the sample number for each template. So it may take very long time to wait if you use the default sample number.
