### ISSUE TITLE
load pretrained model errors

### ISSUE THREAD

**Issue by airsyuan** [microsoft/Table-Pretraining#3]
Dear authors,
Thanks for contributing to the development of table pretraining and release the code. 

When I try to reimplement the code of github，I get a problem of "AttributeError: 'NoneType' object has no attribute 'bpe'". It seems the  load_checkpoint_to_cpu return a NoneType when loading the pretrained model.pt. 
Because state = load_checkpoint_to_cpu(filename, arg_overrides) missing the key "args".

Could you give any advice?

**Comment by SivilTaram** [comment]
@airsYuan Have your issue solved now?

**Comment by SivilTaram** [comment]
For users who meet the same issue, you should firstly check the version of fairseq, which should be `1.0.0a0+801a646` when you use `pip list` to show it.

Note that the fairseq dependency is not officially released as `1.0.0`, so the one is not correct if you directly install it from `pip install fairseq`. Our installtion is equalivant to the following command:
```shell
pip install git+https://github.com/pytorch/fairseq.git@801a64683164680562c77b688d9ca77fc3e0cea7
```
It requires you to have Git installed at first.

Follow-up questions are welcome in this thread. Thanks!

**Comment by airsyuan** [comment]
Sorry for the late reply because of the holiday. When I&nbsp;pip install ***@***.***,the&nbsp;issue is solved.&nbsp;&nbsp;


Thanks very much, and you are a really nice and&nbsp;responsible man.

&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/Table-Pretraining"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月8日(星期五) 中午12:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/Table-Pretraining] load pretrained model errors (#3)





 
For users who meet the same issue, you should firstly check the version of fairseq, which should be 1.0.0a0+801a646 when you use pip list to show it.
 
Note that the fairseq dependency is not officially released as 1.0.0, so the one is not correct if you directly install it from pip install fairseq. Our installtion is equalivant to pip install ***@***.***, which requires you to have Git installed at first.
 
Follow-up questions are welcome in this thread. Thanks!
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SivilTaram** [comment]
@airsYuan Happy to hear that and thanks for your kind words! Other questions about the project are welcome.

**Comment by airsyuan** [comment]
Hi, qian


&nbsp; &nbsp;Thanks&nbsp;again for your kind help&nbsp;to run the code successly.&nbsp;The result is consistent with the paper. Recently, I also learned some papers about nl2sql and I&nbsp;have two questions.
&nbsp; &nbsp;I wonder if we can use the same idea&nbsp; to&nbsp;pretrain a model（not generative model), to replace BERT&nbsp;in some famous nl2sql framework, like X-SQL or SQLNet.&nbsp;&nbsp;
&nbsp; &nbsp;Another idea is that whether we can use this idea for Chinese nl2sql if we translate a sql to a particular Chinese pattern.
&nbsp; &nbsp;I try the first idea using some sample&nbsp;generative sql, but the result is&nbsp;not&nbsp;effective.&nbsp; About the second idea, I am not sure if it works, because Chinese is more complex...
&nbsp; &nbsp; If you have tried those ideas, I would be apperate if you could give some comments about&nbsp;those two sample ideas.


Best,






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/Table-Pretraining"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月9日(星期六) 下午2:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/Table-Pretraining] load pretrained model errors (#3)





 
@airsYuan Happy to hear that and thanks for your kind words! Other questions about the project are welcome.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SivilTaram** [comment]
@airsYuan Hi, very good question!

As discussed in the paper
> The second limitation is that our approach may not benefit the performance of text-to-SQL. We have tried to apply TAPEX on a text-to-SQL dataset, where the input remains the same and the output turns to be SQL. However, TAPEX does not show a significant advantage over BART. We attribute it to two factors: First, our synthetic pre-training corpus does not contribute to grounding, one of the most important factors for semantic parsing (Liu et al., 2021). Second, table reasoning capabilities (e.g., calculation) learned by TAPEX may not be necessary for SQL generation. For example, a model could still understand a NL phrase “total” as the aggregation function “sum”, even though it is unaware of the mathematical meaning of “sum".

So, according to my experience, TAPEX cannot benifit text-to-SQL currently. But, it may enhance the table understanding capacity and it is worthy to try. Follow-up discussions are welcome!

**Comment by airsyuan** [comment]
Thanks, it's very good advice！


About the other question,&nbsp; I am not sure whether it will affect the performance&nbsp;if we rewrite a sql to a sentence according to specific rules. If not, maybe tapex can be&nbsp;applied&nbsp;in other language by&nbsp;translate English sql to corresponding&nbsp;language's&nbsp;statement.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/Table-Pretraining"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月29日(星期五) 晚上9:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/Table-Pretraining] load pretrained model errors (#3)





 
@airsYuan Hi, very good question!
 
As discussed in the paper
  
The second limitation is that our approach may not benefit the performance of text-to-SQL. We have tried to apply TAPEX on a text-to-SQL dataset, where the input remains the same and the output turns to be SQL. However, TAPEX does not show a significant advantage over BART. We attribute it to two factors: First, our synthetic pre-training corpus does not contribute to grounding, one of the most important factors for semantic parsing (Liu et al., 2021). Second, table reasoning capabilities (e.g., calculation) learned by TAPEX may not be necessary for SQL generation. For example, a model could still understand a NL phrase “total” as the aggregation function “sum”, even though it is unaware of the mathemati�cal meaning of “sum".
  
So, according to my experience, TAPEX cannot benifit text-to-SQL currently. But, it may enhance the table understanding capacity and it is worthy to try. Follow-up discussions are welcome!
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SivilTaram** [comment]
@airsYuan An interesting question! I think if the translation is deterministic, the translation from SQL queries into sentences **may benifit the performance**. The key challenge lies in the translation itself: how could we translate a SQL query into a *fluent* natural language? I may recommend you to use SCFG (synchronous context-free grammar) to try it.

BTW, another very interesting way is *directly applying TAPEX on Chinese scenarios*. In other words, we may train a mBART model with only English SQL queries and see if it works on Chinese TableQA. I guess it will work because these tasks with different languages share similar solutions.

Looking forward to your conclusion if you're interested to explore these :-D!

**Comment by airsyuan** [comment]
Thanks, I would like to explore it and share the conclusion&nbsp;if&nbsp;it works!&nbsp;


As mentioned in the reply,&nbsp; it&nbsp;is&nbsp;quite challenging task to translate complex sql to statement. So I&nbsp;try to translate some sample SQL queries to statments as a brief expeirment. For instance, the sample SQL&nbsp; "select xxx from xxx where xxx" can be translate to "当...时，xxx是xxx" according to some rules. However，there is no&nbsp;improvement for the result.


For second advice, does it means we pretrain a mBART with English sql queries, and then replace the SQL&nbsp;queries with Chinese questions to finetune the model?&nbsp; &nbsp;And I am a little confused about&nbsp;whether there is a potential link between the Chinese questions and SQL queries. Could you give me more instructions about it?


Best,




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/Table-Pretraining"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月30日(星期六) 上午10:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/Table-Pretraining] load pretrained model errors (#3)





 
@airsYuan An interesting question! I think if the translation is deterministic, the translation from SQL queries into sentences may benifit the performance. The key challenge lies in the translation itself: how could we translate a SQL query into a fluent natural language? I may recommend you to use SCFG (synchronous context-free grammar) to try it.
 
BTW, another very interesting way is directly applying TAPEX on Chinese scenarios. In other words, we may train a mBART model with only English SQL queries and see if it works on Chinese TableQA. I guess it will work because these tasks with different languages share similar solutions.
 
Looking forward to your conclusion if you're interested to explore these :-D!
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SivilTaram** [comment]
@airsYuan It's interesting that there is no improvement. BTW, do you only translate *simple* SQL queries such as "SELECT A WHERE B = C"? Or you translate all the corpus provided by us.

For the second one, YES. I think the lexicon does not matter in execution pre-training, but the *execution* itself does. Therefore, I think it may work :-D

**Comment by airsyuan** [comment]
Yes, it is. Only the sample SQL queries "select AGG COLUMN from Table where Column OP VALUE" remain, where the complex queries are deleted. Because it is a little hard to translate a complex SQL queries to fluent sentences for quick verification. Any advise on this experiment would be much appreciated.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/Table-Pretraining"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月2日(星期二) 上午9:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/Table-Pretraining] load pretrained model errors (#3)





 
@airsYuan It's interesting that there is no improvement. BTW, do you only translate simple SQL queries such as "SELECT A WHERE B = C"? Or you translate all the corpus provided by us.
 
For the second one, YES. I think the lexicon does not matter in execution pre-training, but the execution itself does. Therefore, I think it may work :-D
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SivilTaram** [comment]
@airsYuan Sorry for the late response since I'm rushing for a conferenece deadline. What kind of datasets are you evaluated on?

**Comment by airsyuan** [comment]
To finetune and evaluate the model in Chinese to SQL downstream task, I choose ZHUIYI&nbsp;dataset, for which most SQL queries are similar like WIKISQL.&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/Table-Pretraining"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月8日(星期一) 下午4:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/Table-Pretraining] load pretrained model errors (#3)





 
@airsYuan Sorry for the late response since I'm rushing for a conferenece deadline. What kind of datasets are you evaluated on?
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SivilTaram** [comment]
@airsYuan Yeah, if the downstream task is also the text-to-SQL, I understand why it does not work. Just as mentioned in the above that:
> We have tried to apply TAPEX on a text-to-SQL dataset, where the input remains the same and the output turns to be SQL. However, TAPEX does not show a significant advantage over BART.

So, I guess you could try a weakly supervised scenario. In other words, there is no SQL but answer for the question. You may see improvement. As for the improvement on text-to-SQL, I'd also very happy to see its improvement if it could be in the near future. More discussions are welcome.

**Comment by SivilTaram** [comment]
Closed since there is no more activity.
