### ISSUE TITLE
How to not encode the entire dataset each time ?

### ISSUE THREAD

**Issue by coderookie1994** [microsoft/Table-Pretraining#32]
On huggingface, each time the entire table is being encoded for every query.
```python
data = {
    "year": [1896, 1900, 1904, 2004, 2008, 2012],
    "city": ["athens", "paris", "st. louis", "athens", "beijing", "london"]
}
table = pd.DataFrame.from_dict(data)

# tapex accepts uncased input since it is pre-trained on the uncased corpus
query = "select year where city = beijing"
encoding = tokenizer(table=table, query=query, return_tensors="pt")
```

How to encode the dataset only once and then query against it multiple times ?

**Comment by SivilTaram** [comment]
@coderookie1994 Thanks for your interest on our work! Since the table will be serialized and be fed into the model at each time, it should be the same even we modify the interface to only encode the table once.

**Comment by coderookie1994** [comment]
> @coderookie1994 Thanks for your interest on our work! Since the table will be serialized and be fed into the model at each time, it should be the same even we modify the interface to only encode the table once.

Sorry could you elaborate a little bit more ?. My doubt is, my table has thousands of rows, each time passing it to the tokenizer will incur a huge cost and also be slow ?. Do we need to reduce the search space by using vector dbs ?

**Comment by SivilTaram** [comment]
@coderookie1994 Okay I see your point. Currently the model may not respond correctly to large databases since its input length can be at most 2k tokens. Maybe you can first truncate the large database into a relatively small one (~40 rows and ~10 cols) for a better performance.

**Comment by coderookie1994** [comment]
> @coderookie1994 Okay I see your point. Currently the model may not respond correctly to large databases since its input length can be at most 2k tokens. Maybe you can first truncate the large database into a relatively small one (~40 rows and ~10 cols) for a better performance.

Yes I figured it out, I am new to this domain. I am using a vector database to get the relevant rows, using that TAPEX works very accurately. Could you suggest any table reader models which would work well with TAPEX ? Currently I am using "deepset/all-mpnet-base-v2-table".  It does the job but would like to know if there is something better that I can use.

**Comment by SivilTaram** [comment]
@coderookie1994 Thanks for your feedback! I'm not sure if there is any better retrieval method 😂 Will let you know if we have better solutions.
