### ISSUE TITLE
Getting started with TAPEX for inference (handling a sum)

### ISSUE THREAD

**Issue by Alcampopiano** [microsoft/Table-Pretraining#33]
Hello and thank you for TAPEX.

I am pretty new to the world of table answering and transformers and am looking for some general thoughts.

When using the pretrained model ([tapex-large-finetuned-wikisql](https://huggingface.co/microsoft/tapex-large-finetuned-wikisql)) TAPEX returns an incorrect sum. 

It is entirely likely that I need to fine tune the model, or perhaps it was not designed to answer these types of questions.

Are you able to help me understand, generally, why this might be the case? 

Any insights would be much appreciated 🙌.

### HuggingFace widget:
<img src="https://github.com/microsoft/Table-Pretraining/assets/4624246/70f4b70b-3480-4b1f-aeec-28ba43b666dc" width="500">

### Python example from docs

```python

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
tokenizer = AutoTokenizer.from_pretrained("microsoft/tapex-large-finetuned-wtq")
model = AutoModelForSeq2SeqLM.from_pretrained("microsoft/tapex-large-finetuned-wtq")

data={'Repository': ['Transformers', 'Datasets', 'Tokenizers'],
      'Stars': ['36542', '4512', '3934'],
      'Contributors': ['651', '77', '34'],
      'Programming language': ['Python', 'Rust', 'NodeJS']
}

table = pd.DataFrame.from_dict(data)

query='what is the sum of stars for the Datasets and Tokenizers repositories?'

encoding = tokenizer(table=table, query=query, return_tensors="pt")

outputs = model.generate(**encoding)

print(tokenizer.batch_decode(outputs, skip_special_tokens=True))
```

# Output:
[' 6338']

# Expected output:
[' 8446']

**Comment by SivilTaram** [comment]
@Alcampopiano Thanks for your interest on our work! Yes it could be true since TAPEX is a generative model. In other words, it generates the sum of results from scratch. It should be also a problem even for ChatGPT models I think.

**Comment by Alcampopiano** [comment]
Thanks very much @SivilTaram. I understand! 

Take care and I will close this issue.
