### ISSUE TITLE
Can' find examples/tableqa/run_model.py in tapex.large.tabfact

### ISSUE THREAD

**Issue by Tizzzzy** [microsoft/Table-Pretraining#34]
Hi,
After I downloaded the fine tuned model "tapex.large.tabfact", I can't find the path examples/tableqa/run_model.py in there. The only three files in "tapex.large.tabfact" are encoder.json, model.pt, vocab.bpe.

**Comment by SivilTaram** [comment]
@Tizzzzy Yes it is true because you should use https://github.com/microsoft/Table-Pretraining/blob/main/examples/tableft/run_model.py for the tabfact task.
