### ISSUE TITLE
A small question about table structure

### ISSUE THREAD

**Issue by boy-be-ambitious** [microsoft/Table-Pretraining#4]
hi, I have a small question, for a new table, how do you know whether the first row or first column or both of them are headers. Do you suppose that we should use a standard table with the first row as headers? Since it may affect the representation of the table. thx!

**Comment by SivilTaram** [comment]
@realize-qzq hi, a very good question! By now we focus on relational (semi-)structured tables for both training and testing, which distinguishs the *headers* and *rows* clearly, so we do not need to identify whether the first row is header.

For practise, if your tabular data does not specify the headers, I would suggest transfering ideas from tabular data understanding tasks (e.g., https://arxiv.org/pdf/2010.12537.pdf) to learn to identify them.

**Comment by boy-be-ambitious** [comment]
> @realize-qzq hi, a very good question! By now we focus on relational (semi-)structured tables for both training and testing, which distinguishs the _headers_ and _rows_ clearly, so we do not need to identify whether the first row is header.
> 
> For practise, if your tabular data does not specify the headers, I would suggest transfering ideas from tabular data understanding tasks (e.g., https://arxiv.org/pdf/2010.12537.pdf) to learn to identify them.

thx! that's what I need.
