### ISSUE TITLE
There is no corresponding script for pretraining on synthetic corpus, right?

### ISSUE THREAD

**Issue by leezythu** [microsoft/Table-Pretraining#5]
Just check if it's missing, Or I could write it by myself.

**Comment by SivilTaram** [comment]
@leezythu Yes it is not provided now. But I can provide one in few days (expected before 10.25).

**Comment by leezythu** [comment]
Thanks a lot.

**Comment by SivilTaram** [comment]
@leezythu Hi, the pre-training script is ready. Hope you enjoy it!
