### ISSUE TITLE
pretrain dataset error

### ISSUE THREAD

**Issue by q5s2c1** [microsoft/Table-Pretraining#7]
Hi，

I meet a problem when I want to pretrain a model via your introduction. Error stacks are as follows.

` File "/home/user/anaconda3/envs/tapex/lib/python3.8/site-packages/fairseq/tasks/translation.py", line 156, in load_langpair_dataset
    return LanguagePairDataset(
  File "/home/user/anaconda3/envs/tapex/lib/python3.8/site-packages/fairseq/data/language_pair_dataset.py", line 232, in __init__
    assert len(src) == len(
AssertionError: Source and target must contain the same number of examples`

I check the preprocess log, and preprocess log is as follows.

`Namespace(align_suffix=None, alignfile=None, all_gather_list_size=16384, amp=False, amp_batch_retries=2, amp_init_scale=128, amp_scale_window=None, azureml_logging=False, bf16=False, bpe=None, cpu=False, criterion='cross_entropy', dataset_impl='mmap', destdir='dataset/pretrain/bart.base/bin', dict_only=False, empty_cache_freq=0, fp16=False, fp16_init_scale=128, fp16_no_flatten_grads=False, fp16_scale_tolerance=0.0, fp16_scale_window=None, joined_dictionary=False, log_file=None, log_format=None, log_interval=100, lr_scheduler='fixed', memory_efficient_bf16=False, memory_efficient_fp16=False, min_loss_scale=0.0001, model_parallel_size=1, no_progress_bar=False, nwordssrc=-1, nwordstgt=-1, on_cpu_convert_precision=False, only_source=False, optimizer=None, padding_factor=8, plasma_path='/tmp/plasma', profile=False, quantization_config_path=None, reset_logging=False, scoring='bleu', seed=1, source_lang='src', srcdict='bart.base/dict.src.txt', suppress_crashes=False, target_lang='tgt', task='translation', tensorboard_logdir=None, testpref=None, tgtdict='bart.base/dict.tgt.txt', threshold_loss_scale=None, thresholdsrc=0, thresholdtgt=0, tokenizer=None, tpu=False, trainpref='dataset/pretrain/train.bpe', use_plasma_view=False, user_dir=None, validpref='dataset/pretrain/valid.bpe', wandb_project=None, workers=1)
[src] Dictionary: 51200 types
[src] dataset/pretrain/train.bpe.src: 4949629 sents, 2195465273 tokens, 0.0% replaced by <unk>
[src] Dictionary: 51200 types
[src] dataset/pretrain/valid.bpe.src: 20000 sents, 8907694 tokens, 0.0% replaced by <unk>
[tgt] Dictionary: 51200 types
[tgt] dataset/pretrain/train.bpe.tgt: 4946227 sents, 31818856 tokens, 0.0% replaced by <unk>
[tgt] Dictionary: 51200 types
[tgt] dataset/pretrain/valid.bpe.tgt: 19987 sents, 127668 tokens, 0.0% replaced by <unk>
Wrote preprocessed data to dataset/pretrain/bart.base/bin`

The difference between train and valid bpe dataset is due to _[num_filtered_EMPTY]_ filtered when preprocessing dataset. So I am not sure if it is right. 
I successfully finish _process_pretrain_data_ step, and some problems occur when I run the script _run_model.py_ in _tapex/examples/pretrain/_ folder.

Could your please tell me which step is wrong?

**Comment by SivilTaram** [comment]
@q5s2c1 Hi, thank you for your interest on our work! I suspect this is caused by the empty outputs. Let me check if the pre-training data have some empty target.

**Comment by SivilTaram** [comment]
@q5s2c1 I have checked that there are empty outputs in the pre-training data. When I perform pre-training, I enable the fairseq option `--keep-empty`, but when I set the default arguments in tapex library, it is missed by me. I will clean the pre-training data and remove the empty lines. It can be done in few hours.

**Comment by SivilTaram** [comment]
@q5s2c1 Hi, I have updated the pre-training corpus, could you kindly delete the pre-training corpus and re-run the script again? Or you can process your data using the following script:

```python
import os

path = "TRAIN_FOLDER_PATH"

train_src = open(os.path.join(path, "train.src"), "r", encoding="utf8")
train_tgt = open(os.path.join(path, "train.tgt"), "r", encoding="utf8")

train_src_new = open(os.path.join(path, "train.new.src"), "w", encoding="utf8")
train_tgt_new = open(os.path.join(path, "train.new.tgt"), "w", encoding="utf8")

counter = 0
for src_line, tgt_line in zip(train_src.readlines(), train_tgt.readlines()):
    if tgt_line.strip() == "":
        continue
    train_src_new.write(src_line)
    train_tgt_new.write(tgt_line)
    counter += 1

train_src_new.close()
train_tgt_new.close()
print(counter)
```

**Comment by q5s2c1** [comment]
> 

Thank you very much！！！ 
I will try it right now.

**Comment by q5s2c1** [comment]
> @q5s2c1 Hi, I have updated the pre-training corpus, could you kindly delete the pre-training corpus and re-run the script again? Or you can process your data using the following script:
> 
> ```python
> import os
> 
> path = "TRAIN_FOLDER_PATH"
> 
> train_src = open(os.path.join(path, "train.src"), "r", encoding="utf8")
> train_tgt = open(os.path.join(path, "train.tgt"), "r", encoding="utf8")
> 
> train_src_new = open(os.path.join(path, "train.new.src"), "w", encoding="utf8")
> train_tgt_new = open(os.path.join(path, "train.new.tgt"), "w", encoding="utf8")
> 
> counter = 0
> for src_line, tgt_line in zip(train_src.readlines(), train_tgt.readlines()):
>     if tgt_line.strip() == "":
>         continue
>     train_src_new.write(src_line)
>     train_tgt_new.write(tgt_line)
>     counter += 1
> 
> train_src_new.close()
> train_tgt_new.close()
> print(counter)
> ```

@SivilTaram Thank you very much!!!
I will try it right now.

**Comment by SivilTaram** [comment]
Hi, @q5s2c1 Is the problem solved now?

**Comment by q5s2c1** [comment]
@SivilTaram yes, it works!!! Thank you.

**Comment by SivilTaram** [comment]
@q5s2c1 Glad to hear that. Enjoy it!
