### ISSUE TITLE
How can I find the code of GETAR？OR GETAR is just same as BART?

### ISSUE THREAD

**Issue by eyuansu62** [microsoft/Table-Pretraining#8]

**Comment by SivilTaram** [comment]
@eyuansu62 Hi, thanks for your interest on our work. This is a good question, and in our latest version we have removed the vague term GETAR because it is actually the BART model.

**Comment by eyuansu62** [comment]
Thanks for your reply!! I have one more question and could you please give me some hints?
Why a pretreating task  aiming exec a SQL can have a promising result on TAbfact task?
Can we draw a conclusion that the core of tab fact task is to find the right column in a table, and this column makes the right decision?

**Comment by SivilTaram** [comment]
@eyuansu62 That is really a good question! From my personal perspective, I think it may be attributed to possible reasons:

- The pre-training corpus contains some (but not a lot) SQL queries which could perform verification-style functions. For example `SELECT (SELECT col1 WHERE col2 = val2) > (SELECT col1 WHERE col2 = val3)`. It will return `1` or `0`.
- The reasoning procedure behind table question answering (TableQA) and table fact verification (TableFV) may be similar. We can regard TableFV as some kind of advanced reasoning on top of TableQA, just as the above example. Meanwhile, from the latest analysis of our paper (https://arxiv.org/pdf/2107.07653.pdf, Appendix C.1), **using simple SQL queries in pre-training help the performance of complex questions** in downstream tasks, we can expect the pre-training of TableQA with SQL (simple tasks) to help the TableFV with NL (complex tasks).

Hope these explaintations bring insights to you! Further discussions are warmly welcome.

**Comment by eyuansu62** [comment]
Very thanks for your reply!!!
